apiVersion: v1
kind: Service
metadata:
  name: spring-demo-svc
  labels:
    app: spring-demo
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: spring-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo-app
  labels:
    app: spring-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-demo
  template:
    metadata:
      labels:
        app: spring-demo
    spec:
      containers:
      - name: spring-demo
        image: localhost:5000/spring-demo:1.0
        ports:
        - containerPort: 8080